# ====================================
# SnowyChunk - Configuration File v26.1.2
# ====================================

database:
  type: sqlite

chunk-protection:
  protection-block: AMETHYST_BLOCK
  hologram-enabled: true

levels:
  1:
    name: "&e⭐ Level 1"
    size: 1
    requirements:
      - type: KILL_MOBS
        amount: 5
  2:
    name: "&6⭐⭐ Level 2"
    size: 4
    requirements:
      - type: KILL_MOBS
        amount: 25